name: PR checks

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    uses: hippoo-app/devops-templates/.github/workflows/validate-plugin.yml@main
    with:
      plugin-slug: hippoo
